[package]
name = "clipass_rs"
version = "0.1.0"
edition = "2024"
description = "Library for masked CLI input reading"
license = "MIT"
repository = "https://github.com/f42h/clipass_rs"

[dependencies]
crossterm = "0.29.0"
md5 = "0.8.0"
sha256 = "1.6.0"
